#!/usr/bin/env bash
set -eu -o pipefail

: <<DESC
Prevent accidental commits to protected branches
DESC

: <<HELP
Mark branches as protected by adding them to a .protected file in the top-level
repository directory. By default, only main is protected.
HELP

shopt -s extglob
protected=$(echo $(cat .protected 2>/dev/null))
protected=${protected:-main}
protected=@(${protected// /|})  # extglob

branch=$(git rev-parse --abbrev-ref HEAD)

case $branch in
  $protected)
    printf "\e[1;33m%s\e[0m\n" "Not allowed to push to the $branch branch"
    exit 1
    ;;
esac