#!/usr/bin/env sh
set -eu -o pipefail

: <<DESC
Prevent non-semantic commit messages
DESC

if [ -z "$1" ]; then
	echo "Missing argument (commit message). Did you try to run this manually?"
	exit 1
fi

commitTitle="$(cat $1 | head -n1)"
echo $commitTitle

# ignore merge requests
if echo "$commitTitle" | grep -qE "^Merge branch \'"; then
	echo "Commit hook: ignoring branch merge"
	exit 0
fi

# check semantic versioning scheme
if ! echo "$commitTitle" | grep -qE '^(?:feat|fix|docs|style|refactor|perf|test|chore)\(?(?:\w+|\s|\-|_)?\)?:\s\w+'; then
  printf "\e[1;33m%s\e[0m\n" "Your commit does not follow https://conventionalcommits.org"
	exit 1
fi